apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello from Azure Kubernetes Service</title>
        <style>
            body {
                font-family: Arial, Helvetica, sans-serif;
            }
            h1 {
                text-align: center;
            }
        </style>
    </head>
    <body>
        <h1>Hello from Azure Kubernetes Service!</h1>

    </body>
    </html>
